name: "Attack and Sustain : Curated Music Videos"
markdown: redcarpet
pygments: false
future: false
exclude: [assets, 'css/scss', deploy, Gemfile, Gemfile.lock, README.md, Rakefile, ey.yml, params.json]
